name: HACS Validation

on:
  push:
    branches:
      - hacs
  pull_request:
    branches:
      - hacs

jobs:
  HACS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
